name: ci
on: push
jobs:
  test:
    permissions:
      # allow the release step to comment on
      # issues, pull requests, and write to the repo
      contents: write
      issues: write
      pull-requests: write
      # Required for OIDC to let NPM registry know
      # that this workflow is trusted
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      # important: the default Node version is v18
      # which gives us an auth error trying to release
      # so install v24 explicitly
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Checkout 🛎
        uses: actions/checkout@v5

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v7
        with:
          build: npx @bahmutov/print-env GITHUB
        env:
          # this token is not tied to any repository
          # and can be used to set the commit status in the repos I have access to
          PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

      - name: Semantic Release 🚀
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v6
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
