name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          build: npx @bahmutov/print-env GITHUB
        env:
          # this token is not tied to any repository
          # and can be used to set the commit status in the repos I have access to
          PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
