name: pr
on:
  # run tests when the user opened / reopened a PR
  # or pushed a new commit (synchronize type)
  # and also run the selected tests when the user possible
  # checked a box with the type of the tests to run
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Run tests 🧪
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v2
        with:
          build: npx @bahmutov/print-env GITHUB
          env: 'pullRequest=${{ github.event.number }}'
        env:
          # this token is not tied to any repository
          # and can be used to set the commit status in the repos I have access to
          PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}

      - name: Print PR body 🖨
        run: |
          node ./bin/get-pr-body.js \
            --owner bahmutov --repo grep-tests-from-pull-requests \
            --pull ${{ github.event.number }}

      - name: Print PR comments 🖨
        run: |
          node ./bin/get-pr-comments.js \
            --owner bahmutov --repo grep-tests-from-pull-requests \
            --pull ${{ github.event.number }}
